### ISSUE TITLE
Activity 4.1.2 Hash Tables: Context

### ISSUE THREAD

**Issue by taimurkashif** [bitprj/curriculum#122]
**1.md**

* Add more to the explanation of a hash function as the current explanation is not in depth enough for a beginner

* Explain the specifics of the diagram given (explicitly state how each of the keys hash to their certain values). Right now, without explanation, we are inferring that the reader fully understands the concept. Given that this is just 1.md and is a new concept for the reader, provide detailed explanation of the diagram.

* Explain in more detail how search and insert become faster, because there doesn't seem to be a clear, beginner-friendly link between discussing what hashing is and how it relates to improved time-complexity for certain functions. Also explain why accessing data is faster (maybe compare to if we had instead stored all the elements in an array?)

**Comment by bitscott1102** [comment]
1.   Hash function is used to map a given value with a particular key for faster access of elements.

2. example of the table
     

-  we use name as keys and number as hashes. Through hash function, keys are connected to hashes. For example, Lisa Smith is connected to 02 in hashes.

3.  In a hash table, data is stored in an array format, where each data value has its own unique index value. Access of data becomes very fast if we know the index of the desired data.
