### ISSUE TITLE
Module4_Labs - Lab6_Sudoku_Solver Card 111: Sudoku grid formatting might be off

### ISSUE THREAD

**Issue by JeffTheAggie** [bitprj/curriculum#324]
This is more of a visual issue based on the printGrid function that was fully created in Card 111. In Card 1, the grid should form the shape of a square, but when I run the code itself, it prints the grid out in the shape of a triangle. I think there might be an issue with how the strings in the print statement and the if-else statements are formatted in the code.

**Comment by bitscott1102** [comment]
It did not print a triangle. It goes as following:

9 4 _ | _ 2 _ | 7 _ _ 
_ _ 1 | _ _ 4 | _ _ 9 
_ _ 6 | _ _ _ | 1 2 _ 
------|-------|-------
_ _ _ | _ _ 3 | _ 1 _ 
1 _ _ | _ _ _ | _ _ 8 
_ 7 _ | 5 _ _ | _ _ _ 
------|-------|-------
_ 8 7 | _ _ _ | 2 _ _ 
6 _ _ | 9 _ _ | 3 _ _ 
_ _ 9 | _ 8 _ | _ 5 7
