### ISSUE TITLE
Module4_Labs - Lab6_Sudoku_Solver Card 61 and 62: These two cards should be in one medium card

### ISSUE THREAD

**Issue by JeffTheAggie** [bitprj/curriculum#331]
This is a styling issue since what both of these cards are supposed to introduce is that hasMoves() is defined as a function that checks if the grid has any zero's in each column. Card 61 shows the actual definition and 62 gives more logic for this function. I believe that both should be on the same card in that case.

**Comment by sarahg500** [comment]
I would say rather than combining the cards, I would add a sentence in 61.md that the function created here will be used in the complete() function and explain that a little bit. This will better separate the cards
