### ISSUE TITLE
Module4_Labs - Lab6_Sudoku_Solver Card 621: hasMoves() isn't a defined function in the code

### ISSUE THREAD

**Issue by JeffTheAggie** [bitprj/curriculum#332]
As I was testing the Sudoku Solver code, I was checking to make sure that the def complete() function works, I got an error within the while loop in which the hasMoves() function isn't defined yet. That should be edited in this card.

**Comment by sarahg500** [comment]
double check when resolving this, but I believe all you would need to do to fix this is tell the student to make sure that the hasMoves() function that they made before in the medium cards is defined above the complete() function.
