### ISSUE TITLE
Module4_Labs - Lab6_Sudoku_Solver Card 711: Copy isn't defined as a function

### ISSUE THREAD

**Issue by JeffTheAggie** [bitprj/curriculum#333]
In Card 711, as I was testing the the Sudoku Solver code with the testPossible() function implemented, the problem here is that copy.deepcopy() isn't defined as a function when you assign this command to the variable "dup".

**Comment by sarahg500** [comment]
when resolving this- make sure to go through the code to see if deepcopy() is made somewhere else in the lab. If it's not, it will probably need to be created. Please message me on slack if it does need to be created. If it is already created, then it most likely just needs to be defined before the testPossible() function.
