### ISSUE TITLE
[Lab 4.6] Sudoku Solver: Convert Easy and Medium Cards Into Steps

### ISSUE THREAD

**Issue by kavuong** [bitprj/curriculum#650]
Please make all medium and easy cards into logical steps - @mxthu313 has more insight

Note from Sarah-
We did a little of this already, but who ever is assigned please make sure the entire lab is cohesive and it has been done for all the medium and easy cards.
easy, medium, and hard cards should also all be balanced so that enough information is in each card to do the steps, the logic should be continuous, etc.

**Comment by sarahg500** [comment]
We did a little of this already, but who ever is assigned please make sure the entire lab is cohesive and it has been done for all the medium and easy cards.

**Comment by sarahg500** [comment]
easy, medium, and hard cards should also all flow correctly so that enough information is in each card to do the steps, the logic should be continuous, etc
